version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install -y unzip wget terraform
#      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
#      - unzip terraform_1.6.6_linux_amd64.zip -d /usr/local/bin/
      - terraform -v # just to print the Terraform version for the logs
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - zip lambda_function_payload.zip index.js
      - terraform plan
      - terraform apply -input=false -auto-approve
